"""Tests for turning registered bloks into agent inputs."""

from dataclasses import dataclass
from typing import Protocol

import pytest

from arkitekt_spec.declare.app import AppRegistry


class RunState:
    """State declared by the protocol the blok depends on."""

    available_protocols: list[str]


class OpentronsLike(Protocol):
    """A remote app the blok drives."""

    RunState: RunState

    def run_protocol(self, protocol: str) -> None:
        """Run a protocol.

        Args:
            protocol (str): The protocol to run.
        """
        ...


@pytest.fixture
def registry() -> AppRegistry:
    """An app that declared the remote protocol its bloks depend on."""
    registry = AppRegistry()
    registry.declare(app="opentrons")(OpentronsLike)
    return registry


# --- demo_state synthesis -------------------------------------------------


def test_demo_state_is_synthesized_for_a_state_with_required_fields(
    registry: AppRegistry,
) -> None:
    @registry.state
    @dataclass
    class ProtocolState:
        available_protocols: list[str]  # required: no default to construct from
        running_protocol: str | None = None

    registry.register_blok(
        "local", '<Text text="@self.ProtocolState.available_protocols" />'
    )

    blok = registry.get_declared_bloks()["local"]

    assert blok.demo_state == {
        "self": {
            "ProtocolState": {"available_protocols": [], "running_protocol": None},
        }
    }


def test_explicit_demo_state_is_left_alone(registry: AppRegistry) -> None:
    @registry.state
    @dataclass
    class ProtocolState:
        available_protocols: list[str]

    registry.register_blok(
        "local",
        '<Text text="@self.ProtocolState.available_protocols" />',
        demo_state={"self": {"ProtocolState": {"available_protocols": ["a"]}}},
    )

    blok = registry.get_declared_bloks()["local"]
    assert blok.demo_state["self"]["ProtocolState"]["available_protocols"] == ["a"]


# --- explicit (cross-app) dependencies ------------------------------------


CROSS_APP_BLOK = """
<foreach items="@opentrons.RunState.available_protocols" let="#protocol">
    <Button label="@protocol" onClick="@opentrons.run_protocol(protocol)" />
</foreach>
"""


def test_cross_app_blok_requires_explicit_dependencies(registry: AppRegistry) -> None:
    registry.register_blok("remote", CROSS_APP_BLOK)

    with pytest.raises(ValueError, match="Blok references unknown action"):
        registry.get_declared_bloks()


def test_explicit_dependency_is_used_verbatim(registry: AppRegistry) -> None:
    registry.register_blok(
        "remote",
        CROSS_APP_BLOK,
        dependencies={"opentrons": OpentronsLike},
    )

    blok = registry.get_declared_bloks()["remote"]
    dependency = blok.dependencies[0]

    assert dependency.key == "opentrons"
    assert dependency.app == "opentrons"
    assert [demand.key for demand in dependency.action_dependencies] == ["run_protocol"]
    assert [demand.key for demand in dependency.state_dependencies] == ["RunState"]


def test_remote_state_is_omitted_from_autogenerated_demo_state(
    registry: AppRegistry,
) -> None:
    # The state has no local definition to synthesize from, and a partial entry
    # would fail the demo_state completeness check.
    registry.register_blok(
        "remote",
        CROSS_APP_BLOK,
        dependencies={"opentrons": OpentronsLike},
    )

    assert registry.get_declared_bloks()["remote"].demo_state == {}


def test_unknown_action_on_an_explicit_dependency_is_rejected(
    registry: AppRegistry,
) -> None:
    registry.register_blok(
        "remote",
        '<Button onClick="@opentrons.run_protokol(1)" />',
        dependencies={"opentrons": OpentronsLike},
    )

    with pytest.raises(ValueError, match="Unknown action 'run_protokol'"):
        registry.get_declared_bloks()


# --- operation naming -----------------------------------------------------


def test_dotted_operation_resolves_to_its_last_segment(registry: AppRegistry) -> None:
    # AppRegistry.implementations is keyed by bare interface, so "ns.run_protocol"
    # names the action "run_protocol". Inference and validation must agree.
    registry.register_blok(
        "remote",
        '<Button onClick="@opentrons.ns.run_protocol(1)" />',
        dependencies={"opentrons": OpentronsLike},
    )

    blok = registry.get_declared_bloks()["remote"]
    assert [demand.key for demand in blok.dependencies[0].action_dependencies] == [
        "run_protocol"
    ]


def test_dotted_operation_with_unknown_last_segment_is_rejected(
    registry: AppRegistry,
) -> None:
    registry.register_blok(
        "remote",
        '<Button onClick="@opentrons.ns.nope(1)" />',
        dependencies={"opentrons": OpentronsLike},
    )

    with pytest.raises(ValueError, match="Unknown action 'nope'"):
        registry.get_declared_bloks()


def test_state_missing_from_an_explicit_dependency_is_rejected(
    registry: AppRegistry,
) -> None:
    # The mirror of the unknown-action check: an explicit dependency is used
    # verbatim, so a state it does not declare must still fail.
    registry.register_blok(
        "remote",
        '<Text text="@opentrons.NopeState.value" />',
        dependencies={"opentrons": OpentronsLike},
    )

    with pytest.raises(ValueError, match="state 'NopeState' does not exist"):
        registry.get_declared_bloks()


# --- local state ----------------------------------------------------------


FORM_BLOK = """
<Card>
    <Slider bind="form.iterations" />
    <Text text="@form.iterations" />
    <Text text="@self.RunStatus.message" />
    <Button label="Run" onClick="@self.run(iterations=form.iterations)" />
</Card>
"""


@pytest.fixture
def runner() -> AppRegistry:
    """An app with one action and one state, for a blok that also keeps a form."""
    registry = AppRegistry()

    @registry.state
    @dataclass
    class RunStatus:
        message: str = ""

    @registry.register
    def run(iterations: int) -> None:
        """Run.

        Args:
            iterations (int): How often.
        """

    return registry


def test_local_state_is_a_path_root_and_no_dependency(runner: AppRegistry) -> None:
    runner.register_blok("form", FORM_BLOK, local_state={"form": {"iterations": 15}})

    blok = runner.get_declared_bloks()["form"]

    assert [dependency.key for dependency in blok.dependencies] == ["self"]


def test_local_state_joins_the_synthesized_demo_state(runner: AppRegistry) -> None:
    runner.register_blok("form", FORM_BLOK, local_state={"form": {"iterations": 15}})

    assert runner.get_declared_bloks()["form"].demo_state == {
        "self": {"RunStatus": {"message": ""}},
        "form": {"iterations": 15},
    }


def test_a_declared_blok_with_local_state_passes_the_agent_checks(
    runner: AppRegistry,
) -> None:
    # The whole declaration is validated again from the wire model, which only
    # knows the demo state.
    runner.register_blok("form", FORM_BLOK, local_state={"form": {"iterations": 15}})

    agent = runner.to_implement_agent_input()

    assert [blok.key for blok in agent.bloks] == ["form"]


def test_a_handwritten_demo_state_key_is_local_state_too(runner: AppRegistry) -> None:
    # What the server accepts: any top-level demo_state key is a path root.
    runner.register_blok(
        "form",
        FORM_BLOK,
        demo_state={
            "self": {"RunStatus": {"message": "idle"}},
            "form": {"iterations": 15},
        },
    )

    blok = runner.get_declared_bloks()["form"]

    assert [dependency.key for dependency in blok.dependencies] == ["self"]
    assert blok.demo_state["form"] == {"iterations": 15}


def test_a_demo_state_key_does_not_make_self_local(runner: AppRegistry) -> None:
    # A typo under `self` must stay an unknown state: `self` is this agent,
    # whatever the demo state says.
    runner.register_blok(
        "form",
        '<Text text="@self.RunStatos.message" />',
        demo_state={"self": {"RunStatos": {"message": ""}}},
    )

    with pytest.raises(ValueError, match="Blok references unknown state 'RunStatos'"):
        runner.get_declared_bloks()


def test_an_undeclared_root_is_still_an_unknown_state(runner: AppRegistry) -> None:
    runner.register_blok("form", FORM_BLOK)

    with pytest.raises(ValueError, match="Blok references unknown state 'iterations'"):
        runner.get_declared_bloks()


@pytest.mark.parametrize("root", ["self", "state", "actions", "utils"])
def test_local_state_cannot_take_a_reserved_root(runner: AppRegistry, root: str) -> None:
    with pytest.raises(ValueError, match="reserved or names a dependency"):
        runner.register_blok("form", "<Card />", local_state={root: {}})


def test_local_state_cannot_take_a_dependency_key(registry: AppRegistry) -> None:
    with pytest.raises(ValueError, match="reserved or names a dependency"):
        registry.register_blok(
            "remote",
            CROSS_APP_BLOK,
            dependencies={"opentrons": OpentronsLike},
            local_state={"opentrons": {}},
        )


def test_local_state_cannot_be_the_target_of_a_call(runner: AppRegistry) -> None:
    runner.register_blok(
        "form", '<Button onClick="@form.run(iterations=1)" />', local_state={"form": {}}
    )

    with pytest.raises(ValueError, match="also the target of an agent call"):
        runner.get_declared_bloks()


def test_demo_state_and_local_state_do_not_overlap(runner: AppRegistry) -> None:
    with pytest.raises(ValueError, match="both demo_state and local_state"):
        runner.register_blok(
            "form", FORM_BLOK, demo_state={"form": {}}, local_state={"form": {}}
        )
